### ISSUE TITLE
When running release aztfmod/rover:2009.0210 have error with AZ CLI

### ISSUE THREAD

**Issue by FreddyAyala** [aztfmod/rover#67]
Hello there, I'm using the latest version of the rover image, I'm using a DevContainer in visual studio code with the following docker-compose:

```
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
 
  version: '3.7'
  services:
    rover:
      image:  aztfmod/rover:2009.0210

    
      labels:
        - "caf=Azure CAF"
   
      volumes:
        - ..:/tf/caf
        - volume-caf-vscode:/home/vscode
        - ~/.ssh:/tmp/.ssh-localhost:ro
   
        - /var/run/docker.sock:/var/run/docker.sock 
   
      # Overrides default command so things don't shut down after the process ends.
      command: /bin/sh -c "while sleep 1000; do :; done" 
   
  volumes:
     volume-caf-vscode:
      labels:
        - "caf=Azure CAF"

  

```

However when trying to do az login, I have the following error:

[vscode@f9b13def0ec9 caf]$ az login
Could not access runpy._run_module_as_main
AttributeError: module 'runpy' has no attribute '_run_module_as_main'

Things worked perfectly in previous releases.
